### ISSUE TITLE
comentarios avance 1

### ISSUE THREAD

**Issue by AliciaMstt** [almamelisa/ProyectoFinalBioinfo-2018-II#1]
Se ve buenos los datos, sin embargo, veo que en el artículo que escogiste ya se hicieron análisis filogenéticos con métodos bayesianos y que incluso hay un Dryad con los datos en los formatos necesarios para hacer esto. ¿En qué difiere tu trabajo de lo que ya se hizo en el artículo?

**Comment by almamelisa** [comment]
Son dos diferencias:

La primera sería que yo pienso utilizar ipyrad para hacer el alineamiento de loci

Segundo ellos obtienen la inferencia filogenética por dos métodos:
-Un árbol de especies con SVDquartets (Chifman and Kubatko 2014).
-Un método basado en coalescencia  con el programa SNAPP(Bryant et al. 2012)

En mi caso se hará se hará un análisis filogenético concatenado y particionado por locus en el programa Mr. Bayes v. 3.2.1, para eso primero tengo que calcular el modelo evolutivo de sustitución de secuencias en el programa jModeltest v.2.17 o con el programa PartionFinder.

Actualmente obtener un árbol de especies y por método de coalescencia es de lo más utilizado para este tipo de datos genéticos, sin embargo, también el método digamos tradicional de árbol de genes sigue siendo utilizado además que mi comité me lo pedirá en forma adicional a los dos anteriores, por eso creo que este sería un buen ejercicio de práctica.

**Comment by AliciaMstt** [comment]
Perfecto, gracias por las aclaraciones.
